name: itksnap

on:
  push:
    paths:
      - ./*
      - .github/workflows/*
  pull_request:
    paths:
      - ./*
      - .github/workflows/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: echo $GITHUB_WORKFLOW
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
